# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eee7d53cb1b202825fd3b0abf41b6e8fe07576e9cd809e0dddaa68438a52b9c6d5097b18c249e77e08a7677b13c620ede7781b722b80ce51c1b7ff24424924a3

test:
  secret_key_base: 7f6bd6df7c04872e64f98333bc1f806c8fce16801f81aa78c5174d2a2af2c403ef2f9063ea4378d1bbc5897ef5d43a9ee9c309997551098f910c55727382a846

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
